### ISSUE TITLE
Eroor with symfony 3.1 and symfony 3.2

### ISSUE THREAD

**Issue by ickbinhier** [snowcap/SnowcapImBundle#31]
Tagged form type extension must have the extended type configured using the extended_type/extended-type attribute, none was configured for the "snowcap_im.form_extension" service.

**Comment by ickbinhier** [comment]
@Moinax 

this problem make a exception under symfony 3.1 and 3.2:

```
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-update-cmd event terminated with an exception

                                                                                                                                                                                                                  
  [RuntimeException]                                                                                                                                                                                              
  An error occurred when executing the "'cache:clear --no-warmup'" command:                                                                                                                                       
  PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: Tagged form type extension must have the extended type configured using the extended_type/extended-type a  
  ttribute, none was configured for the "snowcap_im.form_extension" service. in /var/www/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/FormPass.php:65              
  Stack trace:                                                                                                                                                                                                    
  #0 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php(120): Symfony\Bundle\FrameworkBundle\DependencyInjection\Compiler\FormPass->process(Object(Symfony\Com  
  ponent\DependencyInjection\ContainerBuilder))                                                                                                                                                                   
  #1 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php(565): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\Depende  
  ncyInjection\ContainerBuilder))                                                                                                                                                                                 
  #2 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(484): Symfony\Component\DependencyInjection\ContainerB in /var/www/html/vendor/symfony/symfony/src/Symfony/Bundle/Framewor  
  kBundle/DependencyInjection/Compiler/FormPass.php on line 65
```


in the changelog from symfony find this:

* The alias option of the `form.type_extension` tag is deprecated in favor of
   the `extended_type`/`extended-type` option.

   Before:
   ```xml
   <service id="app.type_extension" class="Vendor\Form\Extension\MyTypeExtension">
       <tag name="form.type_extension" alias="text" />
   </service>
   ```

   After:
   ```xml
   <service id="app.type_extension" class="Vendor\Form\Extension\MyTypeExtension">
       <tag name="form.type_extension" extended-type="Symfony\Component\Form\Extension\Core\Type\TextType" />
   </service>
   ```


i have in the moment th following 2 in file ```Resources/config/services.yml``` line 46  lines remove...
```
        tags:
            -  { name: form.type_extension, alias: snowcap_core_image }
```
But this is definitely not a solution.

**Comment by Moinax** [comment]
Hi @ickbinhier , thank you to make a pull request with the bug fix
